services:
  - type: web
    name: ratemykol-web
    env: node
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: ratemykol-db
          property: connectionString
    autoDeploy: false

databases:
  - name: ratemykol-db
    databaseName: ratemykol
    user: ratemykol_user
    plan: starter