services:
  - type: web
    name: ratemykol-web
    env: node
    plan: starter
    buildCommand: npm ci && npx vite build && npx esbuild server/production.ts --platform=node --packages=external --bundle --format=esm --outdir=dist --outfile=dist/index.js
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: ratemykol-db
          property: connectionString
    autoDeploy: false

databases:
  - name: ratemykol-db
    databaseName: ratemykol
    user: ratemykol_user
    plan: free