services:
  - type: web
    name: ratemykol-web
    env: node
    plan: starter
    buildCommand: npm ci && node build.js
    startCommand: cd dist && npm install --only=prod && npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: ratemykol-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
    autoDeploy: false

databases:
  - name: ratemykol-db
    databaseName: ratemykol
    user: ratemykol_user
    plan: starter